import { GoogleGenAI } from "@google/genai";

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

export interface AnalysisResult {
  sceneDescription: string;
  lightingSetup: string;
  backgroundTextures: string;
  differences?: string;
}

export async function generateProductVisual(
  sourceImageBase64: string,
  analysis: AnalysisResult
): Promise<string> {
  const model = "gemini-2.5-flash-image";
  
  const prompt = `Generate a high-quality professional product photograph based on the following specifications. 
  The product from the provided image should be placed in this new scene.
  
  SCENE COMPOSITION: ${analysis.sceneDescription}
  LIGHTING SETUP: ${analysis.lightingSetup}
  MATERIAL & TEXTURES: ${analysis.backgroundTextures}
  
  Ensure the product's branding and shape are preserved while perfectly integrating it into the lighting and environment described.`;

  const response = await ai.models.generateContent({
    model,
    contents: [
      {
        parts: [
          { text: prompt },
          { inlineData: { mimeType: "image/jpeg", data: sourceImageBase64.split(',')[1] } },
        ],
      },
    ],
  });

  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      return `data:image/png;base64,${part.inlineData.data}`;
    }
  }

  throw new Error("No image was generated by the model.");
}

export async function analyzeProductTransformation(
  sourceImageBase64: string,
  referenceImageBase64: string,
  fidelity: "High Similarity" | "Creative Variation"
): Promise<AnalysisResult> {
  const model = "gemini-3-flash-preview";
  
  const systemInstruction = `You are an AI Product Visualizer Expert. Your goal is to help transform a "Source Product" image to match the aesthetic of a "Reference Style" image.

OPERATIONAL RULES:
1. Analysis Stage: Carefully analyze the 'Source Product' for its shape, scale, and branding. Analyze the 'Reference Image' for its lighting (direction/intensity), color palette (hex codes/mood), environment (props/background), and camera angle.
2. The "Style Fidelity" Logic:
   - If fidelity is "High Similarity": Replicate the reference composition as closely as possible.
   - If fidelity is "Creative Variation": Keep the lighting and color mood, but change the placement of background elements, the type of surface the product sits on, and slightly tweak the camera perspective.
3. Output Format:
   Return a JSON object with the following fields:
   - sceneDescription: A detailed visual description of the new scene.
   - lightingSetup: Specific lighting setup (e.g., Rim lighting, soft shadows).
   - backgroundTextures: Description of background textures (e.g., Matte marble, brushed metal).
   - differences: (Only if fidelity is "Creative Variation") Explain exactly how you made it "different" from the reference.`;

  const prompt = `Analyze these two images and provide the transformation plan for ${fidelity} fidelity.
  
  Source Product: [First Image]
  Reference Style: [Second Image]`;

  const response = await ai.models.generateContent({
    model,
    contents: [
      {
        parts: [
          { text: prompt },
          { inlineData: { mimeType: "image/jpeg", data: sourceImageBase64.split(',')[1] } },
          { inlineData: { mimeType: "image/jpeg", data: referenceImageBase64.split(',')[1] } },
        ],
      },
    ],
    config: {
      systemInstruction,
      responseMimeType: "application/json",
    },
  });

  try {
    return JSON.parse(response.text || "{}") as AnalysisResult;
  } catch (e) {
    console.error("Failed to parse Gemini response", e);
    throw new Error("Failed to analyze images. Please try again.");
  }
}
